services:
  web:
    build:
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - 8000:8000
    volumes:
      - ./django_docker_demo_project:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
  
  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_db: